### ISSUE TITLE
쿠버네티스 세팅

### ISSUE THREAD

**Issue by litsynp** [techeer-f5/jmt-monster-backend#23]

**Comment by DPS0340** [comment]
* EKS 클러스터 초기화
* Slack or Notion으로 인증키 공유
* Docker Image 빌드 툴체인 구성
* Helm으로 클러스터 Deployment 정의 구성
* Argo CD로 Image & Deployment 정의 pull

**Comment by DPS0340** [comment]
[외부 레포](https://github.com/techeer-f5/kubernetes)로 분리하여 작업. 자세한 것은 슬랙 참고
