### ISSUE TITLE
Jackson에 의해 boolean isXXX 값이 is가 제거되어 나오는 이슈

### ISSUE THREAD

**Issue by litsynp** [techeer-f5/jmt-monster-backend#36]
## Issue
- Jackson에 의해 `isSomething` 필드가 자동으로 is가 떼어져서 `something`으로 나오는 것 확인.
- `isHangingOut`으로 의도하고 만든 필드인데 is가 없어지는 것은 의도하지 않았으므로 issue로 게재

## How to Reproduce
친구 요청 생성 -> 친구 요청 수락 -> 친구 조회 시 `isHangingOut`이 `hangingOut`으로 변경되는 것으로 확인

![image](https://user-images.githubusercontent.com/42485462/166636194-cba96baf-c0fd-41be-b6bf-5314f04d6ce3.png)

**Comment by DPS0340** [comment]
@litsynp 제가 맡아도 될까요~?

**Comment by litsynp** [comment]
@DPS0340 넵! 감사해요 👍
