### ISSUE TITLE
행정구역 데이터 Fetch API 구현

### ISSUE THREAD

**Issue by litsynp** [techeer-f5/jmt-monster-backend#63]
## ABOUT
기존에 정적 데이터로 프론트엔드에서 관리하고 있던 **행정구역 JSON 데이터**를 프론트엔드가 아닌 백엔드에서 조회할 수 있도록 API를 제공하도록 한다.

## 구현 사항
- 행정 구역 DTO (Class) 구현
- 행정 구역 정보를 Entity로 구성해 DB 관리
- Spring Batch 등 활용하여 초기 값 init
- `GET` API로 행정 정보 반환 (필요에 따라 caching 적용 with _Redis_)
- 주어진/로그인한 사용자를 확인하여, 각 행정 구역에 대하여 **해당 지역에 거주한 적이 있는지 (행정 구역을 조회할 수 있는지)**, **리뷰를 남길 수 있는지 (현재 그 지역에 살고있는지)** 를 같이 반환할 것
  - 해당 과정에서 사용자 - 행정 구역 다대다 관계 매핑 필요할 것으로 보임

### 추가 사항
- 로그인한 사용자를 확인해서 (또는 RequestParam으로 필터링해서) 실제로 이 행정 구역이 이용 가능한지 값 (isAvailable)이 같이 받아와야 함
  - 필터링할 경우 로그인한 사용자가 해당 사용자가 맞는지 자원에 대한 권한 확인 필요. 권한 없으면 `403 Forbidden` 등 에러 코드 반환
`isAvailable`, `isReadOnly` (가칭) 등 네이밍 필요.

### See Also
#64

**Comment by DPS0340** [comment]
필드 변수가 20개 이상 있어서 gson이나 jackson등으로 파싱하는 것은 무리라고 생각되구요..
이 API가 근본적으로 필요한 이유부터 생각해야 될 듯 한데, 단순히 뿌려주는 데이터를 옮겨주는건 네트워크 병목 문제가 많이 심할 것 같구 (20MB대)
데이터 주입 없이 지역 코드 CRUD만 만들어놓으면 관련된 기능은 문제없지 않을까 생각해 봅니다.

**Comment by DPS0340** [comment]
9차 스프린트의 이사 API (#72)로 대체
