### ISSUE TITLE
API Documentation 라이브러리 선정

### ISSUE THREAD

**Issue by DPS0340** [techeer-f5/jmt-monster-backend#9]
API Spec 명시해주는 라이브러리 후보로는 두 개정도 있음.
* [Spring REST Docs](https://spring.io/guides/gs/testing-restdocs/)
* [OpenAPI 3.0](https://www.baeldung.com/spring-rest-openapi-documentation)

## 차이점 비교
Spring REST Docs는 실제 WAS에 통합 테스트를 실행해서 스펙에 맞춰 WAS의 동작을 보장할 수 있음.
OpenAPI 3.0은 Controller 코드에 명세를 선언해서 추가하는 방식에 가까움.

테스트를 많이 짠다면 Spring REST Docs가 조금 더 선호될 것 같고, 그렇지 않다면 OpenAPI 3.0을 선택하는게 맞는 선택일 듯 함.

**Comment by litsynp** [comment]
제 Swagger 사용 경험으론 Swagger은 확실히 Controller, DTO 쪽에 문서 관련 코드가 들어가다보니 가독성도 그렇고 문서와 코드가 섞여 있어서 분리가 덜 된다는 느낌이 들었습니다! 코드 수정할 때마다 Swagger도 하나씩 변경해야하는데, 수정한 부분과 연관되는 부분을 찾아서 일일히 수동으로 수정해야되는 부분이 많았던 것 같아요.

REST Docs는 테스트 코드쪽에 document를 만드는 부분을 넣는 방식인데, 이 방식이 동작을 보장할 수 있는 만큼 더 좋아보입니다! (다만 설정에 난이도가 좀 있는 것 같아요)

**Comment by DPS0340** [comment]
그렇다면 Spring REST Docs로 문서화시키는 것으로 하겠습니다~! 의견 있으시면 언제나 코멘트 달아주세요!
